### ISSUE TITLE
DBManagement NullPointer

### ISSUE THREAD

**Issue by juanfadev** [Arquisoft/participants_i3b#2]
There is a DBManagement issue. NullPointerException when trying to search for a value that it doesn't exist.

`java.lang.NullPointerException: null
	at DbManagement.DBManagementClass.getParticipant(DBManagementClass.java:22) ~[classes/:na]
	at hello.APIController.user(APIController.java:15) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]`

**Comment by juanfadev** [comment]
Issue closed
